### ISSUE TITLE
Plugin does not build with Gradle 6.2

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#168]
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:xtext-gradle-plugin:classes
\--- :xtext-gradle-plugin:compileJava
     \--- :xtext-gradle-plugin:generateXtext
          \--- :xtext-gradle-plugin:classes (*)

(*) - details omitted (listed previously)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.CircularReferenceException: Circular dependency between the following tasks:
:xtext-gradle-plugin:classes
\--- :xtext-gradle-plugin:compileJava
     \--- :xtext-gradle-plugin:generateXtext
          \--- :xtext-gradle-plugin:classes (*)

(*) - details omitted (listed previously)

@oehme any idea?

**Comment by cdietrich** [comment]
looks like this problem can be solved by using a newer bootstrap version

**Comment by cdietrich** [comment]
but that gives

```
Caused by: java.lang.NoSuchMethodError: org.xtext.gradle.protocol.GradleInstallDebugInfoRequest.getClassesDirs()Lorg/gradle/api/file/FileCollection;
        at org.xtext.gradle.builder.XtextGradleBuilder.lambda$installDebugInfo$31(XtextGradleBuilder.java:532)
        at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
        at org.xtext.gradle.builder.XtextGradleBuilder.installDebugInfo(XtextGradleBuilder.java:561)
        at org.xtext.gradle.tasks.XtextGenerate.installDebugInfo(XtextGenerate.java:373)
        at org.xtext.gradle.XtextBuilderPlugin$4.execute(XtextBuilderPlugin.java:365)
```

**Comment by cdietrich** [comment]
=> i assume we somehow have to build a plugin version that uses gradle 5.x api but how ....

**Comment by cdietrich** [comment]
hmmm doesnt work with 2.0.8 and gralde 5.x neither...
no idea why
with 2.0.6 it does.

version 2.0.8 broken?????

**Comment by cdietrich** [comment]
@oehme any idea why it trys to call getClassesDirs although this method call is no longer in the code?

**Comment by cdietrich** [comment]
now the build of the the android and idea stuff seems to fail....

**Comment by cdietrich** [comment]
```
A problem was found with the configuration of task ':generateXtext'.
> No value has been specified for property 'languages.xtend$0.generator.javaSourceLevel'.
```
seems 

				project.afterEvaluate [p |
					generator.javaSourceLevel = generator.javaSourceLevel ?: java.sourceCompatibility.majorVersion
				]

is bad now

**Comment by oehme** [comment]
That should never be null - Did this work with 6.1 (i.e. with the latest Gradle Plugin version)? If so, can you open a bug report at Gradle? That would hint at some evaluation ordering bug.

**Comment by cdietrich** [comment]
It is set from within the code.
But the check seems to happen before

**Comment by cdietrich** [comment]
@oehme this happens with 6.0 as well. should i file a bug anyway?

**Comment by oehme** [comment]
Yeah that sounds like a bug. The `afterEvaluate` code should run before the task property checks happen.

**Comment by cdietrich** [comment]
problem still there with 6.7
